# **Business Understanding**

**About Data:**
*Development Relevance:* The digital and information revolution has changed the way the world learns, communicates, does business, and treats illnesses. New information and communications technologies (ICT) offer vast opportunities for progress in all walks of life in all countries - opportunities for economic growth, improved health, better service delivery, learning through distance education, and social and cultural advances.

Today's smartphones and tablets have computer power equivalent to that of yesterday's computers and provide a similar range of functions. Device convergence is thus rendering the conventional definition obsolete.

Comparable statistics on access, use, quality, and affordability of ICT are needed to formulate growth-enabling policies for the sector and to monitor and evaluate the sector's impact on development. Although basic access data are available for many countries, in most developing countries little is known about who uses ICT; what they are used for (school, work, business, research, government); and how they affect people and businesses. The global Partnership on Measuring ICT for Development is helping to set standards, harmonize information and communications technology statistics, and build statistical capacity in developing countries. However, despite significant improvements in the developing world, the gap between the ICT haves and have-nots remains.

*Statistical Concept:* The number of in-scope individuals using the Internet is calculated by aggregating the weighted responses. The proportion of individuals using the Internet is expressed as a percentage and is calculated by dividing the total number of in-scope individuals using the Internet by the total number of in-scope individuals, and then multiplying the result by 100.

**Note:**
Weighted average Operators have traditionally been the main source of telecommunications data, so information on subscriptions has been widely available for most countries. This gives a general idea of access, but a more precise measure is the penetration rate - the share of households with access to telecommunications.


[Data source](https://data360.worldbank.org/en/indicator/WB_WDI_IT_NET_USER_ZS?view=datatable&average=WLD&minYear=1990&maxYear=2025)
*Aggregation Method: Weighted average*

#### **Load Libraries**

In [18]:
import pandas as pd   
#  enables us to view all the information sans ellipsisi/ minimization
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

#### **Load Data**

In [3]:
df = pd.read_csv("data/global_internet_usage/WB_WDI_IT_NET_USER_ZS.csv")

# **Data Understanding**

#### **High level view of the data**

In [8]:
df.head()

,STRUCTURE,STRUCTURE_ID,ACTION,FREQ,REF_AREA,INDICATOR,SEX,AGE,URBANISATION,UNIT_MEASURE,COMP_BREAKDOWN_1,COMP_BREAKDOWN_2,COMP_BREAKDOWN_3,TIME_PERIOD,OBS_VALUE,AGG_METHOD,UNIT_TYPE,DECIMALS,DATABASE_ID,TIME_FORMAT,UNIT_MULT,OBS_STATUS,OBS_CONF,FREQ_LABEL,REF_AREA_LABEL,INDICATOR_LABEL,SEX_LABEL,AGE_LABEL,URBANISATION_LABEL,UNIT_MEASURE_LABEL,COMP_BREAKDOWN_1_LABEL,COMP_BREAKDOWN_2_LABEL,COMP_BREAKDOWN_3_LABEL,AGG_METHOD_LABEL,UNIT_TYPE_LABEL,DECIMALS_LABEL,DATABASE_ID_LABEL,TIME_FORMAT_LABEL,UNIT_MULT_LABEL,OBS_STATUS_LABEL,OBS_CONF_LABEL
0,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,UZB,WB_WDI_IT_NET_USER_ZS,_T,_T,_T,PT_POP,_Z,_Z,_Z,1999,0.0307,_Z,RATIO,2,WB_WDI,P1Y,0,A,PU,Annual,Uzbekistan,Individuals using the Internet (% of population),Total,All age ranges or no breakdown by age,Total,Percentage of population,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Ratio,Two,World Development Indicators (WDI),Annual,Units,Normal value,Public
1,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,VUT,WB_WDI_IT_NET_USER_ZS,_T,_T,_T,PT_POP,_Z,_Z,_Z,1999,0.5380,_Z,RATIO,2,WB_WDI,P1Y,0,A,PU,Annual,Vanuatu,Individuals using the Internet (% of population),Total,All age ranges or no breakdown by age,Total,Percentage of population,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Ratio,Two,World Development Indicators (WDI),Annual,Units,Normal value,Public
2,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,VEN,WB_WDI_IT_NET_USER_ZS,_T,_T,_T,PT_POP,_Z,_Z,_Z,1999,2.8400,_Z,RATIO,2,WB_WDI,P1Y,0,A,PU,Annual,"Venezuela, RB",Individuals using the Internet (% of population),Total,All age ranges or no breakdown by age,Total,Percentage of population,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Ratio,Two,World Development Indicators (WDI),Annual,Units,Normal value,Public
3,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,VNM,WB_WDI_IT_NET_USER_ZS,_T,_T,_T,PT_POP,_Z,_Z,_Z,1999,0.1290,_Z,RATIO,2,WB_WDI,P1Y,0,A,PU,Annual,Vietnam,Individuals using the Internet (% of population),Total,All age ranges or no breakdown by age,Total,Percentage of population,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Ratio,Two,World Development Indicators (WDI),Annual,Units,Normal value,Public
4,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,VIR,WB_WDI_IT_NET_USER_ZS,_T,_T,_T,PT_POP,_Z,_Z,_Z,1999,11.1000,_Z,RATIO,2,WB_WDI,P1Y,0,A,PU,Annual,Virgin Islands (U.S.),Individuals using the Internet (% of population),Total,All age ranges or no breakdown by age,Total,Percentage of population,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Ratio,Two,World Development Indicators (WDI),Annual,Units,Normal value,Public

#### **Chekcing the shape(dimensions) of the data frame**

In [39]:
rows, columns = df.shape
output = f"{rows} records and {columns} features"
print(output)

6917 records and 41 features

#### **Extract the columns:**

Reason: The number of columns sem to be quite many, could we narrow down to the relevant columns?

In [22]:
features = df.columns # attaining a list of all the columns/ features
features

Index(['STRUCTURE', 'STRUCTURE_ID', 'ACTION', 'FREQ', 'REF_AREA', 'INDICATOR',
       'SEX', 'AGE', 'URBANISATION', 'UNIT_MEASURE', 'COMP_BREAKDOWN_1',
       'COMP_BREAKDOWN_2', 'COMP_BREAKDOWN_3', 'TIME_PERIOD', 'OBS_VALUE',
       'AGG_METHOD', 'UNIT_TYPE', 'DECIMALS', 'DATABASE_ID', 'TIME_FORMAT',
       'UNIT_MULT', 'OBS_STATUS', 'OBS_CONF', 'FREQ_LABEL', 'REF_AREA_LABEL',
       'INDICATOR_LABEL', 'SEX_LABEL', 'AGE_LABEL', 'URBANISATION_LABEL',
       'UNIT_MEASURE_LABEL', 'COMP_BREAKDOWN_1_LABEL',
       'COMP_BREAKDOWN_2_LABEL', 'COMP_BREAKDOWN_3_LABEL', 'AGG_METHOD_LABEL',
       'UNIT_TYPE_LABEL', 'DECIMALS_LABEL', 'DATABASE_ID_LABEL',
       'TIME_FORMAT_LABEL', 'UNIT_MULT_LABEL', 'OBS_STATUS_LABEL',
       'OBS_CONF_LABEL'],
      dtype='str')

#### **We are checking the number of unique elemets per feature/column:**

Reason: We can drop columns that do not contain constant data(it is the same from the first record to the last record), however, kinldy note there exists algorithms/ techniques that enable feature selection (we shall cpaturethem in AI session)

In [40]:
for feature in features: 
    print(f"FEATURE:{feature} || STATS: {df[feature].nunique()}") # nunique() returns the number of unique items within the columns
    print("===============================")

FEATURE:STRUCTURE || STATS: 1
===============================
FEATURE:STRUCTURE_ID || STATS: 1
===============================
FEATURE:ACTION || STATS: 1
===============================
FEATURE:FREQ || STATS: 1
===============================
FEATURE:REF_AREA || STATS: 246
===============================
FEATURE:INDICATOR || STATS: 1
===============================
FEATURE:SEX || STATS: 1
===============================
FEATURE:AGE || STATS: 1
===============================
FEATURE:URBANISATION || STATS: 1
===============================
FEATURE:UNIT_MEASURE || STATS: 1
===============================
FEATURE:COMP_BREAKDOWN_1 || STATS: 1
===============================
FEATURE:COMP_BREAKDOWN_2 || STATS: 1
===============================
FEATURE:COMP_BREAKDOWN_3 || STATS: 1
===============================
FEATURE:TIME_PERIOD || STATS: 36
===============================
FEATURE:OBS_VALUE || STATS: 5339
===============================
FEATURE:AGG_METHOD || STATS: 1
===============================
FEATURE:UNIT_TYPE || STATS: 1
===============================
FEATURE:DECIMALS || STATS: 1
===============================
FEATURE:DATABASE_ID || STATS: 1
===============================
FEATURE:TIME_FORMAT || STATS: 1
===============================
FEATURE:UNIT_MULT || STATS: 1
===============================
FEATURE:OBS_STATUS || STATS: 1
===============================
FEATURE:OBS_CONF || STATS: 1
===============================
FEATURE:FREQ_LABEL || STATS: 1
===============================
FEATURE:REF_AREA_LABEL || STATS: 246
===============================
FEATURE:INDICATOR_LABEL || STATS: 1
===============================
FEATURE:SEX_LABEL || STATS: 1
===============================
FEATURE:AGE_LABEL || STATS: 1
===============================
FEATURE:URBANISATION_LABEL || STATS: 1
===============================
FEATURE:UNIT_MEASURE_LABEL || STATS: 1
===============================
FEATURE:COMP_BREAKDOWN_1_LABEL || STATS: 1
===============================
FEATURE:COMP_BREAKDOWN_2_LABEL || STATS: 1
===============================
FEATURE:COMP_BREAKDOWN_3_LABEL || STATS: 1
===============================
FEATURE:AGG_METHOD_LABEL || STATS: 1
===============================
FEATURE:UNIT_TYPE_LABEL || STATS: 1
===============================
FEATURE:DECIMALS_LABEL || STATS: 1
===============================
FEATURE:DATABASE_ID_LABEL || STATS: 1
===============================
FEATURE:TIME_FORMAT_LABEL || STATS: 1
===============================
FEATURE:UNIT_MULT_LABEL || STATS: 1
===============================
FEATURE:OBS_STATUS_LABEL || STATS: 1
===============================
FEATURE:OBS_CONF_LABEL || STATS: 1
===============================

#### **Select columns that contained only single values/ 1 unique value and use it to drop their respective columns to cretae a new dataframe**

In [41]:
columns_to_drop = ["OBS_STATUS_LABEL", "OBS_CONF_LABEL","UNIT_MULT_LABEL","TIME_FORMAT_LABEL","DATABASE_ID_LABEL","DECIMALS_LABEL","UNIT_TYPE_LABEL","COMP_BREAKDOWN_3_LABEL","COMP_BREAKDOWN_2_LABEL","COMP_BREAKDOWN_1_LABEL",
"UNIT_MEASURE_LABEL","AGE_LABEL","SEX_LABEL","INDICATOR_LABEL","STRUCTURE", "STRUCTURE_ID","ACTION","FREQ","INDICATOR", "OBS_CONF_LABEL"]

In [36]:
len(columns_to_drop)

20

In [37]:
clean_df = df.drop(columns_to_drop , axis=1) # drop columns,  to make sure we drop purely the olumns we set axis to 1

In [38]:
clean_df.shape

(6917, 22)

#### **Selecting relevant features and creating a new data fram**

In [52]:
relevant_features = ["TIME_PERIOD", "OBS_VALUE","REF_AREA_LABEL"]

In [53]:
clean_df = df[relevant_features] # filtered our tagret columns

In [72]:
rows, columns  = clean_df.shape
output = f"{rows} records and {columns} features"
print(output)

6917 records and 3 features

In [55]:
clean_df.head()

   TIME_PERIOD  OBS_VALUE         REF_AREA_LABEL
0         1999     0.0307             Uzbekistan
1         1999     0.5380                Vanuatu
2         1999     2.8400          Venezuela, RB
3         1999     0.1290                Vietnam
4         1999    11.1000  Virgin Islands (U.S.)

In [56]:
clean_df["TIME_PERIOD"].nunique() # 1990-2025

36

In [57]:
clean_df["OBS_VALUE"].nunique()

5339

In [59]:
clean_df["REF_AREA_LABEL"].nunique()

246

#### **Descriptive stats for numerical values**

In [64]:
clean_df.shape

(6917, 3)

In [69]:
clean_df.dtypes # gives us purely the dtaa types present in the dataste

TIME_PERIOD         int64
OBS_VALUE         float64
REF_AREA_LABEL        str
dtype: object

In [66]:
clean_df.info() # gave us a summary of both  numbe rof non null values per column and data types

<class 'pandas.DataFrame'>
RangeIndex: 6917 entries, 0 to 6916
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   TIME_PERIOD     6917 non-null   int64
 1   OBS_VALUE       6917 non-null   float64
 2   REF_AREA_LABEL  6917 non-null   str
dtypes: float64(1), int64(1), str(1)
memory usage: 162.2 KB

In [61]:
clean_df.describe() # we get descriptive stats for numerical dta types/ columns

       TIME_PERIOD    OBS_VALUE
count  6917.000000  6917.000000
mean   2008.963423    32.464484
std       9.335899    32.137178
min    1990.000000     0.000000
25%    2002.000000     2.434398
50%    2009.000000    21.150000
75%    2017.000000    61.400002
max    2025.000000   100.000000

**Insights:**

*Time Period:*
- Start year was at 1990
- End year was 2025
- 50% of collection was done in 2009
- 25% of the internet data collection happened before 2002
- 75% of the internet data colection happened before 2017

*OB_VALUE:* 
-

#### **Descriptive stats for categorical values**

In [63]:
clean_df.describe(include="object") # we get descriptive stats for atgorical data

/tmp/ipykernel_9102/2423925770.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  clean_df.describe(include="object")

       REF_AREA_LABEL
count            6917
unique            246
top           Austria
freq               36

# **Data Preparation**

# **Modeling**

# **Evaluation**

# **Deployment**